//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolandGarros.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RolandGarros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classement :.
        /// </summary>
        public static string LabelJoueurClassement {
            get {
                return ResourceManager.GetString("LabelJoueurClassement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un classement.
        /// </summary>
        public static string LabelJoueurClassementPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurClassementPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance :.
        /// </summary>
        public static string LabelJoueurDateNaissance {
            get {
                return ResourceManager.GetString("LabelJoueurDateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une date de naissance.
        /// </summary>
        public static string LabelJoueurDateNaissancePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurDateNaissancePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationalité :.
        /// </summary>
        public static string LabelJoueurNationalite {
            get {
                return ResourceManager.GetString("LabelJoueurNationalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une nationalité.
        /// </summary>
        public static string LabelJoueurNationalitePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurNationalitePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string LabelJoueurNom {
            get {
                return ResourceManager.GetString("LabelJoueurNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un nom de famille.
        /// </summary>
        public static string LabelJoueurNomPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurNomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo :.
        /// </summary>
        public static string LabelJoueurPhoto {
            get {
                return ResourceManager.GetString("LabelJoueurPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionner une photo.
        /// </summary>
        public static string LabelJoueurPhotoPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurPhotoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom :.
        /// </summary>
        public static string LabelJoueurPrenom {
            get {
                return ResourceManager.GetString("LabelJoueurPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un prénom.
        /// </summary>
        public static string LabelJoueurPrenomPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurPrenomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe :.
        /// </summary>
        public static string LabelJoueurSexe {
            get {
                return ResourceManager.GetString("LabelJoueurSexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionner le sexe.
        /// </summary>
        public static string LabelJoueurSexePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurSexePrompt", resourceCulture);
            }
        }
    }
}
