//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolandGarros.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RolandGarros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classement.
        /// </summary>
        public static string LabelJoueurClassement {
            get {
                return ResourceManager.GetString("LabelJoueurClassement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un classement.
        /// </summary>
        public static string LabelJoueurClassementPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurClassementPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance.
        /// </summary>
        public static string LabelJoueurDateNaissance {
            get {
                return ResourceManager.GetString("LabelJoueurDateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une date de naissance.
        /// </summary>
        public static string LabelJoueurDateNaissancePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurDateNaissancePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationalité.
        /// </summary>
        public static string LabelJoueurNationalite {
            get {
                return ResourceManager.GetString("LabelJoueurNationalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une nationalité.
        /// </summary>
        public static string LabelJoueurNationalitePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurNationalitePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string LabelJoueurNom {
            get {
                return ResourceManager.GetString("LabelJoueurNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un nom de famille.
        /// </summary>
        public static string LabelJoueurNomPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurNomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string LabelJoueurPhoto {
            get {
                return ResourceManager.GetString("LabelJoueurPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionner une photo.
        /// </summary>
        public static string LabelJoueurPhotoPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurPhotoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string LabelJoueurPrenom {
            get {
                return ResourceManager.GetString("LabelJoueurPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un prénom.
        /// </summary>
        public static string LabelJoueurPrenomPrompt {
            get {
                return ResourceManager.GetString("LabelJoueurPrenomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe.
        /// </summary>
        public static string LabelJoueurSexe {
            get {
                return ResourceManager.GetString("LabelJoueurSexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionner le sexe.
        /// </summary>
        public static string LabelJoueurSexePrompt {
            get {
                return ResourceManager.GetString("LabelJoueurSexePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitre.
        /// </summary>
        public static string LabelMatchArbitre {
            get {
                return ResourceManager.GetString("LabelMatchArbitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir un arbitre.
        /// </summary>
        public static string LabelMatchArbitrePrompt {
            get {
                return ResourceManager.GetString("LabelMatchArbitrePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Court.
        /// </summary>
        public static string LabelMatchCourt {
            get {
                return ResourceManager.GetString("LabelMatchCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir un court.
        /// </summary>
        public static string LabelMatchCourtPrompt {
            get {
                return ResourceManager.GetString("LabelMatchCourtPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string LabelMatchDate {
            get {
                return ResourceManager.GetString("LabelMatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une date.
        /// </summary>
        public static string LabelMatchDatePrompt {
            get {
                return ResourceManager.GetString("LabelMatchDatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueur.
        /// </summary>
        public static string LabelMatchJoueur1 {
            get {
                return ResourceManager.GetString("LabelMatchJoueur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le premier joueur.
        /// </summary>
        public static string LabelMatchJoueur1Prompt {
            get {
                return ResourceManager.GetString("LabelMatchJoueur1Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueur.
        /// </summary>
        public static string LabelMatchJoueur2 {
            get {
                return ResourceManager.GetString("LabelMatchJoueur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le second joueur.
        /// </summary>
        public static string LabelMatchJoueur2Prompt {
            get {
                return ResourceManager.GetString("LabelMatchJoueur2Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous-tournoi.
        /// </summary>
        public static string LabelMatchSousTournoi {
            get {
                return ResourceManager.GetString("LabelMatchSousTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir un sous-tournoi.
        /// </summary>
        public static string LabelMatchSousTournoiPrompt {
            get {
                return ResourceManager.GetString("LabelMatchSousTournoiPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée.
        /// </summary>
        public static string LabelResultatDuree {
            get {
                return ResourceManager.GetString("LabelResultatDuree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir une durée.
        /// </summary>
        public static string LabelResultatDureePrompt {
            get {
                return ResourceManager.GetString("LabelResultatDureePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gagnant.
        /// </summary>
        public static string LabelResultatGagnant {
            get {
                return ResourceManager.GetString("LabelResultatGagnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le gagnant.
        /// </summary>
        public static string LabelResultatGagnantPrompt {
            get {
                return ResourceManager.GetString("LabelResultatGagnantPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultat.
        /// </summary>
        public static string LabelResultatSetsGagnesJoueur1 {
            get {
                return ResourceManager.GetString("LabelResultatSetsGagnesJoueur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir le résultat.
        /// </summary>
        public static string LabelResultatSetsGagnesJoueur1Prompt {
            get {
                return ResourceManager.GetString("LabelResultatSetsGagnesJoueur1Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultat.
        /// </summary>
        public static string LabelResultatSetsGagnesJoueur2 {
            get {
                return ResourceManager.GetString("LabelResultatSetsGagnesJoueur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir le résultat.
        /// </summary>
        public static string LabelResultatSetsGagnesJoueur2Prompt {
            get {
                return ResourceManager.GetString("LabelResultatSetsGagnesJoueur2Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perdant.
        /// </summary>
        public static string LabelResultatSetsPerdants {
            get {
                return ResourceManager.GetString("LabelResultatSetsPerdants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le perdant.
        /// </summary>
        public static string LabelResultatSetsPerdantsPrompt {
            get {
                return ResourceManager.GetString("LabelResultatSetsPerdantsPrompt", resourceCulture);
            }
        }
    }
}
